Lab1
inmistlosted/metaprogramming pull request #1
Opened 2020-10-12 21:39 UTC by inmistlosted

Лабораторна №1

2020-10-15 15:49 UTC, hoherchak requested changes
Не вдалося успішно відформатувати навіть код, який подано в вашому репозиторії. Перевірте будь ласка роботу.
Також прохання додати readme як і домовлялися.
В цій лабі не потрібно мати інтерактивне введення, мається на увазі виклик у вигляді `python3 main.py -f <шаблон> -d <каталог>` і так далі за текстом лаби. Перевірте це також будь ласка.
Під шаблоном мається на увазі набір значень для усіх параметрів, а не певні блоки конфігурації як у вас. Тобто має бути можливість підставити будь-який конфігураційний файл.

2020-10-18 21:04 UTC, hoherchak requested changes
Перевірте `python3 main.py -f resources/templates-settings.json resources/input-code.js`:
```
Traceback (most recent call last):
  File "main.py", line 25, in <module>
    resultFile = FileReader.writeToFile(path, result)
  File "/Users/hryhoriihoherchak/Documents/labs/Podvazhuk/metaprogramming/Lab1/filereader.py", line 69, in writeToFile
    directoryPath = re.match(r'[A-Za-z]:/(\w+/)*', inputFileName).group(0)
AttributeError: 'NoneType' object has no attribute 'group'
```
Для ConvexHull.js те саме.

2020-10-22 15:43 UTC, inmistlosted commented
можливо у Вас так запрацює

2020-10-22 21:20 UTC, hoherchak requested changes
Ви обмежуєте крос-платформеність утиліти способом обробки шляхів до файлу. Використовуйте вбудовану бібліотеку os для цього замість регулярних виразів чи будь-яких інших хуків.
Також прохання прибрати з git файли віртуального оточення, їх в репозиторії бути не повинно.
Чекаю на робочу версію.

2020-10-25 17:26 UTC, inmistlosted commented
Обробка шляхів здійснюється за допомогою бібліотеки os. У мене програма успішно запускається, можливо Вам потрібно відкрити її в pyCharm і додати інтерпретатор. З python працюю вперше, тому не знаю, які там можуть виникати помилки і чому не виходить у Вас запустити.

2020-10-25 19:24 UTC, hoherchak requested changes

2020-10-25 19:24 UTC, hoherchak commented on Lab1/filereader.py
> +        directoryPath = re.match(r'[A-Za-z]:/(\w+/)*', inputFileName).group(0)
Ось наприклад в цьому місці не os, а регулярні вирази.

2020-10-25 19:24 UTC, hoherchak commented on Lab1/filereader.py
> +        directoryPath = re.match(r'[A-Za-z]:/(\w+/)*', inputFileName).group(0)
Воно у вас запускається, бо у вас Windows.

2020-10-26 21:32 UTC, hoherchak requested changes
Врахуйте коментарі та змініть утиліту так, щоб форматування здійснювалося в тому ж файлі, а не створювався новий.
Також відсутні опції щодо форматування/верифікації каталогів та проектів.
Допрацьовуйте, поки на мінімум цього недостатньо, але частина зі вказаних зауважень скоріш за все легко виправляється.

2020-10-26 21:32 UTC, hoherchak commented on Lab1/resources/templates-settings.json
> +      "AssignmentOperators": true,
Чомусь оператори перескочують в коді на інше місце.

2020-10-26 21:32 UTC, hoherchak commented on Lab1/resources/templates-settings.json
> +      "AlignWhenMultiline": false,
Щось дивне відбувається для такого коду:
```
this.fThree({strA: 'a',
strB: 'b',
strC: 'c',
strD: 'd'
}, 'strE');
```

2020-10-26 21:32 UTC, hoherchak commented on Lab1/resources/templates-settings.json
> +      "ElseOnNewLine": false,
Частково команди ігноруються, наприклад ElseOnNewLine.

2020-10-26 21:32 UTC, hoherchak commented on Lab1/resources/templates-settings.json
> +      "InCode": 2
Опція не впливає.

2020-10-26 21:32 UTC, hoherchak commented on Lab1/resources/templates-settings.json
> +    }
Те саме для опцій вище.

2020-10-26 21:33 UTC, hoherchak commented
І прохання прибрати теки з бібліотеками з git, це погана практика.

2020-10-30 21:04 UTC, hoherchak commented
@inmistlosted Буду більш конкретним: приберіть теку `venv` :)

2020-10-30 21:58 UTC, hoherchak commented
@inmistlosted  Як буде готово до перевірки, не забудьте повторно запитати рев'ю.

2020-10-30 22:04 UTC, inmistlosted commented
Для того щоб форматувати/верифікувати каталоги та проекти потрібно замість шляху до файлу ввести шлях до самого каталогу, тоді всі файли там відформатуються/верифікуються

2020-10-30 22:18 UTC, hoherchak commented on Lab1/resources/templates-settings.json
> +      "ElseOnNewLine": false,
@inmistlosted це був натяк що потрібно зробити, а не видалити з конфігу :)

2020-10-30 22:19 UTC, hoherchak commented on Lab1/resources/templates-settings.json
> +      "InCode": 2
Аналогічно.

2020-10-30 22:20 UTC, hoherchak commented on Lab1/resources/templates-settings.json
> +    }
Аналогічно.

2020-10-30 22:28 UTC, hoherchak requested changes
Частина попередніх коментарів не врахована.
Зверніть увагу на форматування коду, який поданий в один рядок. Він повинен розгортатися (відповідно до параметрів) у структурне подання з табуляціями. Також відсутня реакція на перевищення кількості порожніх рядків.
Також чомусь у вас все ще в одному з режимів замість табуляції дефіси.
При форматуванні проекту [freeCodeCamp](https://github.com/freeCodeCamp/freeCodeCamp) виникає помилка:
```
Traceback (most recent call last):
  File "/Users/hryhoriihoherchak/Documents/labs/Podvazhuk/metaprogramming/Lab1/main.py", line 32, in <module>
    lexer.execute()
  File "/Users/hryhoriihoherchak/Documents/labs/Podvazhuk/metaprogramming/Lab1/Lexer/lexer.py", line 27, in execute
    currStringCopy = self.__findSymbols(currStringCopy)
  File "/Users/hryhoriihoherchak/Documents/labs/Podvazhuk/metaprogramming/Lab1/Lexer/lexer.py", line 110, in __findSymbols
    string = string[0:matcher.start()] + string[matcher.end():]
AttributeError: 'NoneType' object has no attribute 'start'
```
Поки все ще недостатньо на мінімум. Нагадую, що вже знімаються штрафні бали, тому не затягуйте з виправленнями.

2020-10-31 20:04 UTC, inmistlosted commented
Додав розгортання та виправив помилку на freeCodeCamp. Дефіси налаштовуються в шаблоні UseTabsCharacter, якщо поставити false, то дефісів не буде

2020-10-31 21:30 UTC, hoherchak requested changes
Знов та сама проблема: бекслеш в шляхах є тільки в Windows. Виправте перевірку на каталог з використанням модуля os.
Також табуляція це ж не дефіс, правда? Тож треба відкоригувати також.

2020-10-31 22:45 UTC, inmistlosted commented
Зробив перевірку на каталог за допомогою os. Символ дефіз використовується лише щоб візуально показати табуляцію, як це здійснюється в шаблоні в intellij idea, на жаль не можу придумати більш вдалого способу це показати

2020-10-31 22:54 UTC, hoherchak requested changes
Так, обробка проекту працює, але деякі файли форматуються некоректно.
Ось приклад:
```
module.exports = {
  host: '127.0.0.1',
  sessionSecret: process.env.SESSION_SECRET,

  github: {
    clientID: process.env.GITHUB_ID,
    clientSecret: process.env.GITHUB_SECRET
  }
};
```
Рядок чомусь "стрибає" на початок файлу.
Щодо табуляцій - то цей параметр регулює чи здійснюється табулювання пробілами або ж символами \t.

2020-11-01 13:47 UTC, hoherchak requested changes
Частково помилки виправлені, але все одно дуже в багатьох файлах тієї бібліотеки форматувальник переміщує частини коду.
На 7 цього достатньо, але якщо хочете 8 - потрібно це виправити. Дайте знати чи будете виправляти.

2020-11-01 14:17 UTC, inmistlosted commented
Згоден на 7 балів

2020-11-01 14:18 UTC, hoherchak approved these changes
Готуйтесь до захисту на найближчій парі.

2020-11-01 14:21 UTC, inmistlosted commented
Добре, дякую

2020-12-06 18:41 UTC, merged