added lab3
inmistlosted/metaprogramming pull request #3
Opened 2020-12-06 20:51 UTC by inmistlosted

2020-12-06 21:57 UTC, hoherchak requested changes
Прохання врахувати коментарі та додати відповідність типів python типам обраного вами діалекту SQL. Це частина лаби.
Також ви вбили історію комітів, прохання зробити rebase і пофіксити саме ту попередню гілку.

2020-12-06 21:57 UTC, hoherchak commented on Lab3/Py2SQL/Py2SQL.py
> +        sql = f"""select *
Тут мався на увазі виклик типу `Py2SQL.find_objects_by(table, id=3, name='dsfsdf', type='abc')`

2020-12-06 21:57 UTC, hoherchak commented on Lab3/Py2SQL/Py2SQL.py
> +                        from {table})
id об'єкта в такому разі буде "плаваючим", що не дуже добре
краще передбачити обов'язкову наявність відповідного поля в таблиці і викидати exception якщо немає такого поля чи такого значення в ньому

2020-12-07 18:13 UTC, inmistlosted commented
Я дуже вибачаюсь, але не вдається відновити минулі коміти, тому що для того, щоб створити новий пул реквест без зайвих змін, довелося видалити стару гілку

2020-12-07 19:23 UTC, hoherchak requested changes
@inmistlosted Ви можете зробити [update-ref](https://stackoverflow.com/questions/5471174/move-branch-pointer-to-different-commit-without-checkout). Історія комітів з git не видаляється навіть при видаленні гілки.
Візьміть останній хеш [тут](https://github.com/inmistlosted/metaprogramming/pull/2) та відновіть гілку з нього. Потім змерджіть master в цю гілку і зробіть так, щоб різниця з master була тільки в каталозі третьої лаби.
Захист призначив на завтра, перевірте календар та підтвердіть.
Помилки здається враховані, перевіряти треті лаби на виконання буду згодом.

2020-12-14 23:16 UTC, hoherchak approved these changes

2020-12-17 16:59 UTC, closed without merging